### ISSUE TITLE
No retention policy is defined to `metrics` bucket in the InfluxDB

### ISSUE THREAD

**Issue by ateska** [TeskaLabs/asab-maestro-library#21]
https://github.com/TeskaLabs/asab-maestro-library/blob/54fae580b4127c91b3a6395d65909bd5080cf4eb/Site/ASAB%20Maestro/Descriptors/influxdb.yaml#L17

I propose to set that to 180 days:

```shell
$ podman exec -it influxdb-1 influx bucket create --name metrics --org system --retention 180d
 ```
^- manual creation

**Comment by eliska-n** [comment]
default retention policy can eb set in the docker compose, but i need to test it first

```
      - INFLUXDB_RETENTION_ENABLED=true
      - INFLUXDB_INIT_RETENTION=2h
      - DOCKER_INFLUXDB_INIT_RETENTION=2h
  ```
